services:
  mongodb:
    image: mongo:7
    container_name: mongodb
    environment:
      # Authenticated variant, comment out for non-authenticated variant:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=fdm-root
    ports:
      - "21111:27017"
    volumes:
      - ./fdm-monster:/data
    restart: unless-stopped

  fdm-monster:
    container_name: fdm-monster
    image: davidzwa/fdm-monster:develop
    build:
      context: .
      dockerfile: docker/Dockerfile
    restart: unless-stopped
    deploy:
      restart_policy:
        delay: 5s
        max_attempts: 3
        window: 120s
    ports:
      - "4000:4000"
    environment:
      # Non-authenticated variant:
#      - MONGO=mongodb://mongodb:27017/fdm-monster
      # Authenticated variant:
      - MONGO=mongodb://root:fdm-root@mongodb:27017/fdm-monster?authSource=admin
      - NODE_ENV=development
      - SERVER_PORT=4000
    volumes:
      - ./fdm-monster/media/:/app/media
